### PR TITLE
Add UI for Configuration and Fix iTach Flex Support

### PR DESCRIPTION
**Pull request by SiobhanBaynes**
I’ve fixed the iTach Flex support so you can now select which channel to send the IR command to. I’ve also added a simple UI for maintaining devices and config.

### CODE REVIEW

**Comment by plarsson** [comment]
Great, thanks for the PR! I will look in more detail asap when I have access to a homey.. Is the UI also supporting relay and serial?

**Comment by SiobhanBaynes** [comment]
Thanks. As best I can from the info I had. Basically it builds up the same JSON that you had in the raw format.

**Comment by SiobhanBaynes** [comment]
Hi Peter,

Did you manager to review my PR? Is there anything I can do to improve it? I’d love to get this live to share it with the community!

Thanks,

Siobhan.

On 17 Jul 2019, at 20:39, Peter Larsson <notifications@github.com<mailto:notifications@github.com>> wrote:


Great, thanks for the PR! I will look in more detail asap when I have access to a homey.. Is the UI also supporting relay and serial?

**Comment by plarsson** [comment]
Hi Siobhan,  

Yes I'll look into this later this week. I've been on vacation, sorry for the delay

**Comment by plarsson** [comment]
Hi finally got some time testing this, seems to work fine :) 
I was thinking that we should add the correct images (svg) for the Flex? For the iTach I requested help from homey directly, they have a very helpful service at  https://github.com/athombv/homey-vectors-public

My previous issue #: https://github.com/athombv/homey-vectors-public/issues/39 .

Could you request Flex svgs there ?

and again sorry for the delay reviewing this

**Comment by SiobhanBaynes** [comment]
Awesome, thanks! I was wondering where everyone got those images from.

I’ll request them and resubmit the PR.

Kind regards,

Siobhan.

On 12 Aug 2019, at 20:12, Peter Larsson <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi finally got some time testing this, seems to work fine :)
I was thinking that we should add the correct images (svg) for the Flex? For the iTach I requested help from homey directly, they have a very helpful service at https://github.com/athombv/homey-vectors-public

My previous issue #: athombv/homey-vectors-public#39<https://github.com/athombv/homey-vectors-public/issues/39> .

Could you request Flex svgs there ?

and again sorry for the delay reviewing this

**Comment by plarsson** [comment]
Ok great, you don't need to resubmit the whole PR, just add new commits to your branch and they will show up here in this PR.

**Comment by SiobhanBaynes** [comment]
I've updated both the svg and the jpegs, thanks :)

**Review by plarsson — APPROVED** [review]
lgtm

**Comment by plarsson** [comment]
released now in homey app store

**Comment by SiobhanBaynes** [comment]
Awesome, thanks!

On 21 Aug 2019, at 14:32, Peter Larsson <notifications@github.com<mailto:notifications@github.com>> wrote:


released now in homey app store

**Pull request merged**
